version: '2'

volumes:
  # MySQL Data
  tickets-mysql-data:
    driver: local

services:

  mysql:
    image: ambientum/mysql:5.7
    container_name: tickets-db
    volumes:
      - tickets-mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tickets
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

  app:
    image: ambientum/php:7.2-nginx
    container_name: tickets-app
    volumes:
      - .:/var/www/app
    ports:
      - "8000:8080"
    links:
      - mysql